import { useQuery } from '@tanstack/react-query';
import api from '../api/axios';
import { motion } from 'framer-motion';
import { Target, Grid3X3, Users, Zap } from 'lucide-react';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1, delayChildren: 0.2 },
  },
};

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5 },
  },
};

export default function Segments() {
  const { data: segments, isLoading } = useQuery({
    queryKey: ['segments'],
    queryFn: () => api.get('/api/segments').then(r => r.data),
    refetchInterval: 5000
  });

  return (
    <div style={{ padding: '32px 24px', maxWidth: '1400px', margin: '0 auto' }}>
      <motion.div 
        className="page-header"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="page-header-left">
          <h2>Audience Segments</h2>
          <p>Created by you or intelligently generated by AI</p>
        </div>
      </motion.div>

      {isLoading ? (
        <motion.div 
          style={{ textAlign: 'center', padding: '60px 24px' }}
          animate={{ opacity: [0.5, 1, 0.5] }}
          transition={{ duration: 1.5, repeat: Infinity }}
        >
          <div style={{ fontSize: 40, marginBottom: 12 }}>⟳</div>
          <p style={{ color: 'var(--t2)' }}>Loading segments...</p>
        </motion.div>
      ) : (
        <>
          {(!segments || segments.length === 0) ? (
            <motion.div 
              className="card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              style={{ textAlign: 'center', padding: '60px 24px' }}
            >
              <div style={{ fontSize: 48, marginBottom: 16 }}>🎯</div>
              <h3 style={{ fontSize: 18, fontWeight: 700, color: 'var(--t1)', marginBottom: 8 }}>No segments yet</h3>
              <p style={{ color: 'var(--t2)', marginBottom: 8 }}>Let the AI Agent create smart segments based on customer behavior and spending patterns</p>
              <p style={{ color: 'var(--t3)', fontSize: 13 }}>Or create custom segments based on specific rules</p>
            </motion.div>
          ) : (
            <motion.div
              className="grid"
              variants={containerVariants}
              initial="hidden"
              animate="visible"
            >
              {segments.map((s, idx) => (
                <motion.div
                  key={s._id}
                  className="card"
                  variants={cardVariants}
                  whileHover={{ y: -8, boxShadow: 'var(--sh2)' }}
                  style={{ display: 'flex', flexDirection: 'column' }}
                >
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 16 }}>
                    <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start', flex: 1 }}>
                      <div style={{
                        width: 48,
                        height: 48,
                        background: 'linear-gradient(135deg, rgba(108,99,255,.2), rgba(139,133,255,.1))',
                        borderRadius: 12,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: '#1e40af',
                        flexShrink: 0
                      }}>
                        <Target size={24} />
                      </div>
                      <div style={{ flex: 1 }}>
                        <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--t1)', marginBottom: 4 }}>{s.name}</h3>
                        <p style={{ fontSize: 13, color: 'var(--t2)', marginBottom: 12 }}>{s.description || '—'}</p>
                      </div>
                    </div>
                  </div>

                  <div style={{ display: 'flex', gap: 12, marginBottom: 16, flexWrap: 'wrap' }}>
                    <div style={{ flex: 1, minWidth: 120, background: 'var(--bg2)', padding: 12, borderRadius: 8 }}>
                      <div style={{ fontSize: 11, color: 'var(--t3)', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Audience Size</div>
                      <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--p)' }}>{s.audienceSize}</div>
                      <div style={{ fontSize: 11, color: 'var(--t3)', marginTop: 4 }}>customers</div>
                    </div>
                    <div style={{ flex: 1, minWidth: 120, background: 'var(--bg2)', padding: 12, borderRadius: 8 }}>
                      <div style={{ fontSize: 11, color: 'var(--t3)', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Logic</div>
                      <div style={{ 
                        fontSize: 16, 
                        fontWeight: 700, 
                        color: s.logicOperator === 'OR' ? '#f59e0b' : '#3b82f6',
                        display: 'flex',
                        alignItems: 'center',
                        gap: 6
                      }}>
                        <Zap size={16} />
                        {s.logicOperator}
                      </div>
                    </div>
                  </div>

                  <div style={{ background: 'var(--bg2)', padding: 12, borderRadius: 8, flex: 1 }}>
                    <div style={{ fontSize: 11, color: 'var(--t3)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Rules</div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                      {(s.rules || []).map((r, i) => (
                        <motion.div
                          key={i}
                          style={{
                            fontSize: 12,
                            color: 'var(--t2)',
                            padding: 8,
                            background: 'rgba(108,99,255,.05)',
                            borderRadius: 6,
                            borderLeft: '3px solid rgba(108,99,255,.3)'
                          }}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.05 }}
                        >
                          <strong>{r.field}</strong> {r.operator} <code style={{ background: 'var(--card)', padding: '2px 6px', borderRadius: 3, color: '#1e40af', fontWeight: 600 }}>{String(r.value)}</code>
                        </motion.div>
                      ))}
                    </div>
                  </div>

                  <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid var(--bd)', fontSize: 12, color: 'var(--t3)' }}>
                    Created {new Date(s.createdAt).toLocaleDateString()}
                  </div>
                </motion.div>
              ))}
            </motion.div>
          )}
        </>
      )}
    </div>
  );
}